baseURL = "/"
languageCode = "en-us"
title = "Vihreä työelämä 2020-luvulla"
theme = "kube"
description = "Mielestämme Vihreiden tulisi ottaa ryhtiliike työmarkkinapolitiikassa. Esitämme haasteita joista kukaan ei vielä puhu fiksusti. Me Vihreät voisimme."
Paginate = 20
pluralizelisttitles = "false"
[Params]
  RSSLink = "/index.xml"
  author = "Jori Mäkkeli, Janne Peltola, Juho Salmi ja Jussi-Pekka Teini" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""

[[menu.main]]
    name = "Kirja"
    weight = 1
    url = "/kirja/"
[[menu.main]]
    name = "Kirjoittajat"
    weight = 2
    url = "/kirjoittajat/"
[[menu.main]]
    name = "UKK"
    weight = 3
    url = "/faq/"
[[menu.main]]
    name = "Keskusteluryhmä"
    weight = 4
    url = "https://chat.whatsapp.com/Jtdivjf9XsA3rs5lR1SJUx"